#!/bin/bash

dims () {
	if [ $# -gt 1 ]; then
		echo "Too many arguments supplied" >&2 
	 	return 1 
	elif [ $# = 0 ]; then
		cat > "temp$$" 
		dims "temp$$"
		rm -f "temp$$"
	else
		if [ -r $1 ]; then
			rows=0
			columns=0
			while read myLine
			do
				if [ $rows = 0 ]; then
					for i in $myLine
					do
						columns=`expr $columns + 1`
					done
				fi
				rows=`expr $rows + 1`
			done < $1
			echo -e "$rows $columns"
		else
			echo "The file is not readable" >&2
			return 1
		fi
	fi
}

transpose () {
	if [ $# -gt 1 ]; then
		echo "Too many arguments supplied" >&2 
	 	return 1 
	elif [ $# = 0 ]; then
		cat > "transpose$$" 
		transpose "transpose$$"
		rm -f "transpose$$"
	else
		if [ -r $1 ]; then
			columns=0
			read myLine < $1
			for i in $myLine
			do
				columns=`expr $columns + 1`
			done
			tempCol="tempColFile"
			tempT="tempFile"

			cut -f 1 $1 > "holder"
			head --byte -1 "holder" > $tempCol
			cat $tempCol | tr '\n' '\t' > "tempRow$$"
			echo -e "" >> "tempRow$$"
			count=2
			while [ $count -le $columns ]
			do
			#	echo "$count"
				cut -f $count $1 > "holder"
				head --byte -1 "holder" > $tempCol
				cat $tempCol | tr '\n' '\t' >> "tempRow$$"
				echo -e "" >> "tempRow$$"
				count=`expr $count + 1`
			done
			cat "tempRow$$"
			rm -f "tempRow$$"
		else
			echo "The file is not readable" >&2
			return 1
		fi
	fi

} 

mean () {
	if [ $# -gt 1 ]; then
		echo "Too many arguments supplied" >&2 
	 	return 1 
	elif [ $# = 0 ]; then
		cat > "mean$$" 
		mean "mean$$"
		rm -f "mean$$"
	else
		if [ -r $1 ]; then
			sum=0
			avg=0
			count=1
			elements=`wc -w $1 | cut -f1 -d' '`
			lines=`wc -l $1 | cut -f1 -d' '`
			columns=`expr $elements / $lines`
		#	echo "lines: $lines"
		#	echo "columns: $columns"
			cat /dev/null > "tempAvg"
			while [ $count -le $columns ]
			do
			cut -f $count $1 > "testmean"
			while read myLine
			do
				for i in $myLine
				do
					sum=`expr $sum + $i`
				done
			done < "testmean"
		#	echo "sum: $sum"
			avg=`expr $sum / $lines`
		#	echo "$avg" 
			#round the number
			roundlines=`expr $lines + 1`
			rounder=`expr $roundlines / 2`
		#	echo "rounder: $rounder"
		#	echo "modlines: $roundlines from $lines"
			mod=$(( $sum % $lines ))
		#	echo "modulu: $mod"
			if [ $mod -ge 0 ]; then
				if [ $mod -ge $rounder ]; then
					avg=`expr $avg + 1`
				fi
			elif [ $mod -lt 0 ]; then
				if [ $mod -le $rounder ]; then
					avg=`expr $avg - 1`
				fi
			fi
				
	#		avg=`expr \( $sum + $lines / 2 \) \* \( \( $sum > 0 \) \* 2 - 1 \) \) / $lines`
		#	echo "$avg"
			echo "$avg" >> "tempAvg"
			sum=0
			count=`expr $count + 1`
			done
			cat "tempAvg" | tr '\n' '\t' > "holder"  
			head --byte -1 "holder" > "mean$$"
			echo -e "" >> "mean$$"
			cat "mean$$"
		else
			echo "The file is not readable" >&2
			return 1
		fi
	fi
}

$1 "${@:2}"

